

# Basic
name:               "UST Ultrasound"
title:              "The Hong Kong University of Science and Technology"
description:        "this is a page for UST Ultrasound lab, xxx"


# URL
url:               
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "members"
    href:           "/members"
  - name:           "research"
    href:           "/research"
  - name:           "publications"
    href:           "/publication"
  - name:           "opening"
    href:           "/opening"
  - name:           "gallery"
    href:           "/gallery"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  -
    scope:
      path:         ""
      type:         "slides"
    values:
      layout:       "iframe"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
  slides:
    output: true

    
